### Retorna todos los productos de la colección
GET http://localhost:3000/api/users

### Retorna un producto en específico
GET http://localhost:3000/api/users/1

### Crea un nuevo producto
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Product 2"
}

### Actualiza un producto
PUT http://localhost:3000/api/users/3
Content-Type: application/json

{
  "name": "Vanessa"
}

### Elimina un producto
DELETE http://localhost:3000/api/users/2

### Elimina todos los productos de la colección
DELETE http://localhost:3000/api/users/