### Retorna todos los productos de la colección
GET http://localhost:3000/api/products

### Retorna un producto en específico
GET http://localhost:3000/api/products/6297804e5922972765c3267d

### Crea un nuevo producto
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "Product 2",
  "description": "Product 2 description",
  "rut": "22042308-5",
  "stock": "10",
  "price": "100000",
  "description": "Product 1 description",
  "email": "me@mail.com"
}

### Actualiza un producto
PUT http://localhost:3000/api/products/629046f75d5ccffa9d380724
Content-Type: application/json

{
  "name": "Product 4",
  "description": "Product 4 description",
  "price": "30.00"
}

### Elimina un producto
DELETE http://localhost:3000/api/products/62977e4fc9978c3fdd43a559

### Elimina todos los productos de la colección
DELETE http://localhost:3000/api/products/