### DATABASE MONGODB

### Retorna todos los productos de la colección
GET http://localhost:3000/api/products

### Retorna un producto en específico
GET http://localhost:3000/api/products/629f5b6bcd120d46e7711a6d

### Crea un nuevo producto
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "Product 5",
  "description": "Product 2 description",
  "rut": "22541308-5",
  "stock": "10",
  "price": "100000",
  "description": "Product 1 description",
  "email": "m24@mail.com"
}

### Actualiza un producto
PUT http://localhost:3000/api/products/629f56e65db58f9a976ad929
Content-Type: application/json

{
  "name": "Product 4",
  "description": "Product 4 description",
  "price": "30.00"
}

### Elimina un producto
DELETE http://localhost:3000/api/products/629f5a960a5cebff0028d46

### Elimina todos los productos de la colección
DELETE http://localhost:3000/api/products/